name = "Apophis"
uuid = "b41c07a2-2abb-11e9-070a-c3c1b239e7df"
authors = ["Jorge Pérez <PerezHz@users.noreply.github.com>", "Luis Benet <lbenet@users.noreply.github.com>"]
version = "0.1.0"

[deps]
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"
